export type Language='EN'|'HI';
let language:Language='EN';
try{language=localStorage.getItem('JIYA_LANGUAGE')==='HI'?'HI':'EN';}catch{}
export const getLanguage=()=>language;
export function setLocale(value:Language){language=value;try{localStorage.setItem('JIYA_LANGUAGE',value);}catch{}if(typeof document!=='undefined')document.documentElement.lang=value==='HI'?'hi':'en';}
const phrases:Record<string,string>={
 'Language':'भाषा','Profile':'प्रोफ़ाइल','Sign out':'साइन आउट','Account menu':'खाता मेन्यू','Your account':'आपका खाता','Back to dashboard':'डैशबोर्ड पर वापस जाएँ','Update your personal details.':'अपनी व्यक्तिगत जानकारी बदलें।','Full name':'पूरा नाम','Username':'उपयोगकर्ता नाम','Phone':'फ़ोन','Email':'ईमेल','Save profile':'प्रोफ़ाइल सहेजें','Saving…':'सहेज रहे हैं…','Profile updated successfully.':'प्रोफ़ाइल अपडेट हो गई।',
 'Client Entry':'ग्राहक जोड़ें','Add Customer':'ग्राहक जोड़ें','Customers':'ग्राहक','Customer':'ग्राहक','Clients':'ग्राहक','Client':'ग्राहक','POS Bill':'बिल बनाएँ','POS Billing':'बिलिंग','Eye Checkup':'आँखों की जाँच','Eye Testing':'आँखों की जाँच','Inventory':'स्टॉक','Follow-ups':'फ़ॉलो-अप','Dashboard':'डैशबोर्ड','Purchases':'खरीद','Masters & Settings':'मास्टर्स और सेटिंग्स','All Branches':'सभी दुकानें','Choose a shop to continue':'आगे बढ़ने के लिए दुकान चुनें','Manage shops':'दुकानों का प्रबंधन','Team & access':'टीम और पहुँच',
 'Monthly revenue & collections':'मासिक बिक्री और प्राप्त भुगतान','All accessible shops combined':'आपकी सभी दुकानों का कुल विवरण','Revenue':'बिक्री','Received':'प्राप्त भुगतान','Pending now':'अभी बकाया','Year':'वर्ष','No billing or receipt activity for this year yet.':'इस वर्ष अभी कोई बिल या भुगतान दर्ज नहीं है।','Today Sales':'आज की बिक्री','Net Cash Today':'आज की नकद राशि','Active Orders':'चालू ऑर्डर','Khata Dues':'खाते का बकाया','Pending Balance':'बकाया राशि','Low Stock':'कम स्टॉक','View':'देखें','Manage':'प्रबंधन','New Bill':'नया बिल',
 'Refraction Details':'नज़र की जाँच का विवरण','Patient':'मरीज़','Add patient':'मरीज़ जोड़ें','Add doctor':'डॉक्टर जोड़ें','Optometrist / Doctor':'ऑप्टोमेट्रिस्ट / डॉक्टर','Choose doctor':'डॉक्टर चुनें','-- Choose Patient --':'-- मरीज़ चुनें --','Vision Power Matrix':'नज़र की पावर','Snellen Acuity':'दृष्टि की स्पष्टता','Eye':'आँख','Sphere (SPH)':'स्फीयर (SPH)','Cylinder (CYL)':'सिलिंडर (CYL)','Axis (°)':'अक्ष (°)','Addition (ADD)':'ऐड पावर (ADD)','Right (OD)':'दायाँ (OD)','Left (OS)':'बायाँ (OS)','Recommended Lens Type':'लेंस का प्रकार','Lens Coating':'लेंस की कोटिंग','PD (mm)':'पुतलियों की दूरी (मिमी)','Notes / Remarks':'नोट्स / टिप्पणी','Next Checkup':'अगली जाँच','Save Prescription':'पर्चा सहेजें','Recent Prescriptions':'हाल के पर्चे','Qualification':'योग्यता','Mobile number':'मोबाइल नंबर',
 'Item Master & Material Inventory':'मटेरियल और स्टॉक','One material catalogue. Separate stock, purchases and sales for each shop.':'मटेरियल एक बार जोड़ें। हर दुकान का स्टॉक, खरीद और बिक्री अलग ट्रैक करें।','Create Material':'मटेरियल जोड़ें','Create New Material / Item':'नया मटेरियल जोड़ें','Edit Master Material':'मटेरियल बदलें','Import CSV':'CSV आयात करें','Export CSV':'CSV निर्यात करें','Branch Stock View:':'दुकान का स्टॉक:','Material / Item Details':'मटेरियल का विवरण','Shop Branch':'दुकान','Opening stock shop':'शुरुआती स्टॉक की दुकान','Barcode / SKU':'बारकोड / SKU','Material / Product Title':'मटेरियल का नाम','Brand / Manufacturer':'ब्रांड / निर्माता','Model / Article No.':'मॉडल / आर्टिकल नंबर','Color / Shade':'रंग','Frame Type':'फ़्रेम का प्रकार','Size Specs / Base Curve':'साइज़ / बेस कर्व','HSN Code':'HSN कोड','Purchase Price (₹)':'खरीद मूल्य (₹)','Sale Price (₹)':'बिक्री मूल्य (₹)','Initial Stock Qty':'शुरुआती स्टॉक','Low Stock Alert':'कम स्टॉक की सीमा','Rack / Shelf Location':'रैक / शेल्फ़','Material details and selling price are shared across shops. Opening quantity, cost and rack belong to the selected shop.':'मटेरियल की जानकारी और बिक्री मूल्य सभी दुकानों में समान हैं। शुरुआती मात्रा, लागत और रैक चुनी हुई दुकान के लिए हैं।',
 'Physical Stock':'कुल स्टॉक','Cost Valuation':'स्टॉक की लागत','Retail Value':'बिक्री मूल्य','Unique SKUs':'अलग मटेरियल','TOTAL UNITS':'कुल इकाइयाँ','Stock':'स्टॉक','Category':'श्रेणी','Actions':'कार्य','Search name, brand, barcode...':'नाम, ब्रांड या बारकोड खोजें…','Inter-Branch Stock Transfer':'दुकानों के बीच स्टॉक ट्रांसफ़र','Destination Branch':'स्टॉक भेजने की दुकान','Quantity to Transfer':'भेजने की मात्रा','Transfer Stock':'स्टॉक भेजें','Adjust Stock':'स्टॉक बदलें','Current Stock':'मौजूदा स्टॉक','Current Location':'मौजूदा स्थान','New Quantity':'नई मात्रा',
 'Record Supplier Inward Purchase Bill':'सप्लायर से खरीद दर्ज करें','Receiving shop':'स्टॉक प्राप्त करने वाली दुकान','Choose a shop':'दुकान चुनें','Stock increases only in this shop. Changing shops clears the selected items.':'स्टॉक केवल इस दुकान में बढ़ेगा। दुकान बदलने पर चुने हुए आइटम हट जाएँगे।','Select Supplier':'सप्लायर चुनें','-- Choose Supplier --':'-- सप्लायर चुनें --','Supplier Bill / Invoice #':'सप्लायर बिल नंबर','Bill Date':'बिल की तारीख','Add Product Line Item':'खरीद में मटेरियल जोड़ें','Product':'मटेरियल','-- Select Product --':'-- मटेरियल चुनें --','Qty Inward':'प्राप्त मात्रा','Cost Rate (₹)':'खरीद दर (₹)','Add Item':'आइटम जोड़ें','Total Bill Amount:':'बिल की कुल राशि:','Amount Paid Now (₹)':'अभी किया भुगतान (₹)','Balance Due:':'बकाया राशि:','Save Inward Purchase & Update Stock':'खरीद सहेजें और स्टॉक अपडेट करें',
 'Cancel':'रद्द करें','Save':'सहेजें','Save Changes':'बदलाव सहेजें','Close':'बंद करें','Delete':'हटाएँ','Edit':'बदलें','Search':'खोजें','Print':'प्रिंट करें','Submit':'जमा करें','Refresh':'रीफ़्रेश करें','Name':'नाम','Date':'तारीख','Time':'समय','Total':'कुल','Amount':'राशि','Paid':'भुगतान किया','Balance':'बकाया','Quantity':'मात्रा','Discount':'छूट','Payment':'भुगतान','Payment Mode':'भुगतान का तरीका','Cash':'नकद','Order':'ऑर्डर','Status':'स्थिति','Supplier':'सप्लायर','Doctor':'डॉक्टर','Address':'पता','City':'शहर','State':'राज्य','Mobile':'मोबाइल','Notes':'नोट्स','Details':'विवरण','Settings':'सेटिंग्स','Team':'टीम','Users':'उपयोगकर्ता','User':'उपयोगकर्ता','Role':'भूमिका','Branch':'दुकान','Shops':'दुकानें','Shop':'दुकान','Materials':'मटेरियल','Products':'मटेरियल','Material':'मटेरियल','Units':'इकाइयाँ','Bills':'बिल','Orders':'ऑर्डर','Collection':'वसूली','Collections':'वसूली','Expenses':'खर्च','Expense':'खर्च','Receipt':'रसीद','Invoice':'बिल','Invoices':'बिल','Outstanding':'बकाया','Pending':'लंबित','Delivery':'डिलीवरी','Contact':'संपर्क','Brand':'ब्रांड','Barcode':'बारकोड','Model':'मॉडल','Color':'रंग','Location':'स्थान','Cost':'लागत','Sale':'बिक्री','Purchase':'खरीद','Stock Transfer':'स्टॉक ट्रांसफ़र','Select':'चुनें','Choose':'चुनें','All':'सभी','New':'नया','Add':'जोड़ें','Create':'बनाएँ','Update':'अपडेट करें','Download':'डाउनलोड','Upload':'अपलोड','Filter':'फ़िल्टर','History':'इतिहास','Summary':'सारांश','Reports':'रिपोर्ट','Report':'रिपोर्ट','Print Invoice':'बिल प्रिंट करें','Save & Print':'सहेजें और प्रिंट करें','Save Bill':'बिल सहेजें','Generate Invoice':'बिल बनाएँ','Customer Details':'ग्राहक की जानकारी','Customer Name':'ग्राहक का नाम','Patient Name':'मरीज़ का नाम','Grand Total':'कुल राशि','Net Payable':'देय राशि','Advance Paid':'अग्रिम भुगतान','Balance Due':'बकाया राशि','Fitting Charge':'फ़िटिंग शुल्क','Flat Discount':'कुल छूट','Order Notes':'ऑर्डर नोट्स','Payment Reference':'भुगतान संदर्भ','Delivery Date':'डिलीवरी की तारीख','Direct Sale':'सीधी बिक्री','Order Booked':'ऑर्डर दर्ज','In Progress':'काम जारी','Delivered':'डिलीवर हुआ','Cancelled':'रद्द','Ready for Delivery':'डिलीवरी के लिए तैयार','Fitting Done':'फ़िटिंग पूरी',
};
const entries=Object.entries(phrases).sort((a,b)=>b[0].length-a[0].length);
const cache=new Map<string,string>();
export function t(text:string):string {
  text=text.replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&nbsp;/g,' ').replace(/&#39;/g,"'").replace(/&quot;/g,'"');
  if(language==='EN')return text.replace(/\bClient Entry\b/g,'Add Client').replace(/\bCustomers\b/g,'Clients').replace(/\bCustomer\b/g,'Client').replace(/\bcustomers\b/g,'clients').replace(/\bcustomer\b/g,'client');
  if(cache.has(text))return cache.get(text)!;
  const direct=phrases[text.trim()]||entries.find(([key])=>key.toLowerCase()===text.trim().toLowerCase())?.[1];
  if(direct)return text.replace(text.trim(),direct);
  // Translate only developer-authored UI literals. Customer/product data is never passed here.
  let result=text;
  for(const [key,value] of entries) result=result.replace(new RegExp('(?<![A-Za-z])'+key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?![A-Za-z])','gi'),value);
  cache.set(text,result);return result;
}
