import {useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
import {cloudErrorMessage} from '../lib/cloudErrors';
export function JoinApprovals({ownerId,shops,canReview}:{ownerId:string;shops:{id:string;name:string}[];canReview:boolean}){
  const [requests,setRequests]=useState<{userId:string;email:string;shopId:string}[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;const load=async()=>{const r=await supabase!.rpc('optical_join_pending',{team_owner:ownerId});if(!active)return;if(r.error)setError(cloudErrorMessage(r.error));else {setRequests(r.data);setError('');}};void load();const timer=setInterval(load,10000);return()=>{active=false;clearInterval(timer);};},[ownerId]);
  const review=async(userId:string,approve:boolean)=>{if(busy||!canReview)return;setBusy(true);try{const r=await supabase!.rpc('optical_join_review',{team_owner:ownerId,applicant:userId,approve});if(r.error)throw r.error;window.location.reload();}catch(e){setError(cloudErrorMessage(e));setBusy(false);}};
  return <section className="bg-white border border-amber-200 rounded-2xl p-5 space-y-4"><h2 className="font-bold text-lg">Joining requests ({requests.length})</h2><p className="text-sm text-stone-500">Approve a request to grant access to the selected shop only.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}{!requests.length&&!error&&<p>No pending requests.</p>}{requests.map(r=><div key={r.userId} className="flex flex-wrap items-center gap-3 border-t pt-3"><div className="flex-1"><strong>{r.email}</strong><p className="text-sm">{shops.find(s=>s.id===r.shopId)?.name||'Shop no longer available'}</p></div><button disabled={busy||!canReview} onClick={()=>review(r.userId,true)} className="bg-amber-700 text-white px-4 py-2 rounded-lg disabled:opacity-50">Approve</button><button disabled={busy||!canReview} onClick={()=>review(r.userId,false)} className="border px-4 py-2 rounded-lg disabled:opacity-50">Reject</button></div>)}</section>;
}
