import { t } from '../lib/i18n';
import React,{useState} from 'react';
import {Plus,X} from 'lucide-react';
import {useApp} from '../context/AppContext';
export function QuickAddPerson({kind,onClose,onAdded}:{kind:'patient'|'doctor';onClose:()=>void;onAdded:(id:string)=>void}){
  const {addCustomer,addDoctor,currentUser,isCloud}=useApp();
  const [name,setName]=useState(''),[mobile,setMobile]=useState(''),[qualification,setQualification]=useState(''),[error,setError]=useState('');
  return <div className="fixed inset-0 z-50 bg-slate-950/35 backdrop-blur-sm grid place-items-center p-4"><form role="dialog" aria-modal="true" aria-label={kind==='patient'?'Add patient':'Add doctor'} className="bg-white rounded-3xl p-6 max-w-md w-full space-y-5 shadow-xl" onSubmit={e=>{e.preventDefault();setError('');try{if(kind==='patient'){const person=addCustomer({name:name.trim(),mobile:mobile.trim()});onAdded(person.id);}else{if(isCloud&&currentUser.role!=='Admin')throw Error('Ask an admin to add a doctor to the shared directory.');addDoctor({name:name.trim(),mobile:mobile.trim(),qualification:qualification.trim(),commissionPercent:0,isActive:true});onAdded(name.trim());}onClose();}catch(err){setError(err instanceof Error?err.message:'Could not add record.');}}}><header className="flex items-center justify-between"><h2 className="text-xl font-semibold">{kind==='patient'?t("Add patient"):t("Add doctor")}</h2><button type="button" aria-label={t("Close")} onClick={onClose}><X className="w-5 h-5"/></button></header><label className="block text-sm">{t("Full name")}<input autoFocus required value={name} onChange={e=>setName(e.target.value)} className="mt-2 border rounded-xl p-3 w-full"/></label><label className="block text-sm">{t("Mobile number")}<input required type="tel" value={mobile} onChange={e=>setMobile(e.target.value)} className="mt-2 border rounded-xl p-3 w-full"/></label>{kind==='doctor'&&<label className="block text-sm">{t("Qualification")}<input value={qualification} onChange={e=>setQualification(e.target.value)} className="mt-2 border rounded-xl p-3 w-full"/></label>}{error&&<p role="alert" className="text-rose-600 text-sm">{error}</p>}<button className="bg-amber-700 text-white rounded-xl w-full p-3 flex items-center justify-center gap-2"><Plus className="w-4 h-4"/>{kind==='patient'?t("Add patient"):t("Add doctor")}</button></form></div>;
}
